// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrkszotwheoxuevsjsku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhya3N6b3R3aGVveHVldnNqc2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjUxNTUsImV4cCI6MjA1OTQwMTE1NX0.CAM5_nLqs0vQo_Hl6gKoCCwgf3wghgjHUfnDG9YkIAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);